# coding: utf-8

"""
    speechapi

    Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_voicerecognition_api_client
from cloudmersive_voicerecognition_api_client.models.token_timestamp import TokenTimestamp  # noqa: E501
from cloudmersive_voicerecognition_api_client.rest import ApiException


class TestTokenTimestamp(unittest.TestCase):
    """TokenTimestamp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenTimestamp(self):
        """Test TokenTimestamp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_voicerecognition_api_client.models.token_timestamp.TokenTimestamp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
