# coding: utf-8

"""
    speechapi

    Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TokenTimestamp(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'token': 'str',
        'character_offset_start': 'int',
        'character_offset_end': 'int',
        'start_time_ms': 'int',
        'end_time_ms': 'int'
    }

    attribute_map = {
        'token': 'Token',
        'character_offset_start': 'CharacterOffsetStart',
        'character_offset_end': 'CharacterOffsetEnd',
        'start_time_ms': 'StartTimeMs',
        'end_time_ms': 'EndTimeMs'
    }

    def __init__(self, token=None, character_offset_start=None, character_offset_end=None, start_time_ms=None, end_time_ms=None):  # noqa: E501
        """TokenTimestamp - a model defined in Swagger"""  # noqa: E501

        self._token = None
        self._character_offset_start = None
        self._character_offset_end = None
        self._start_time_ms = None
        self._end_time_ms = None
        self.discriminator = None

        if token is not None:
            self.token = token
        if character_offset_start is not None:
            self.character_offset_start = character_offset_start
        if character_offset_end is not None:
            self.character_offset_end = character_offset_end
        if start_time_ms is not None:
            self.start_time_ms = start_time_ms
        if end_time_ms is not None:
            self.end_time_ms = end_time_ms

    @property
    def token(self):
        """Gets the token of this TokenTimestamp.  # noqa: E501

        The token text (word or subword)  # noqa: E501

        :return: The token of this TokenTimestamp.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this TokenTimestamp.

        The token text (word or subword)  # noqa: E501

        :param token: The token of this TokenTimestamp.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def character_offset_start(self):
        """Gets the character_offset_start of this TokenTimestamp.  # noqa: E501

        Start character offset (0-based) in TextResult  # noqa: E501

        :return: The character_offset_start of this TokenTimestamp.  # noqa: E501
        :rtype: int
        """
        return self._character_offset_start

    @character_offset_start.setter
    def character_offset_start(self, character_offset_start):
        """Sets the character_offset_start of this TokenTimestamp.

        Start character offset (0-based) in TextResult  # noqa: E501

        :param character_offset_start: The character_offset_start of this TokenTimestamp.  # noqa: E501
        :type: int
        """

        self._character_offset_start = character_offset_start

    @property
    def character_offset_end(self):
        """Gets the character_offset_end of this TokenTimestamp.  # noqa: E501

        End character offset (exclusive) in TextResult  # noqa: E501

        :return: The character_offset_end of this TokenTimestamp.  # noqa: E501
        :rtype: int
        """
        return self._character_offset_end

    @character_offset_end.setter
    def character_offset_end(self, character_offset_end):
        """Sets the character_offset_end of this TokenTimestamp.

        End character offset (exclusive) in TextResult  # noqa: E501

        :param character_offset_end: The character_offset_end of this TokenTimestamp.  # noqa: E501
        :type: int
        """

        self._character_offset_end = character_offset_end

    @property
    def start_time_ms(self):
        """Gets the start_time_ms of this TokenTimestamp.  # noqa: E501

        Start time of this token in the audio, in milliseconds  # noqa: E501

        :return: The start_time_ms of this TokenTimestamp.  # noqa: E501
        :rtype: int
        """
        return self._start_time_ms

    @start_time_ms.setter
    def start_time_ms(self, start_time_ms):
        """Sets the start_time_ms of this TokenTimestamp.

        Start time of this token in the audio, in milliseconds  # noqa: E501

        :param start_time_ms: The start_time_ms of this TokenTimestamp.  # noqa: E501
        :type: int
        """

        self._start_time_ms = start_time_ms

    @property
    def end_time_ms(self):
        """Gets the end_time_ms of this TokenTimestamp.  # noqa: E501

        End time of this token in the audio, in milliseconds  # noqa: E501

        :return: The end_time_ms of this TokenTimestamp.  # noqa: E501
        :rtype: int
        """
        return self._end_time_ms

    @end_time_ms.setter
    def end_time_ms(self, end_time_ms):
        """Sets the end_time_ms of this TokenTimestamp.

        End time of this token in the audio, in milliseconds  # noqa: E501

        :param end_time_ms: The end_time_ms of this TokenTimestamp.  # noqa: E501
        :type: int
        """

        self._end_time_ms = end_time_ms

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TokenTimestamp, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TokenTimestamp):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
